apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
spec:
  selector:
    matchLabels:
      app: ecommerce-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
      - name: vanshika_ecommerce
        image: 854171615125.dkr.ecr.eu-north-1.amazonaws.com/vanshika_ecommerce:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-app
spec:
  selector:
    app: ecommerce-app
  ports:
    - port: 8080
      targetPort: 8080